version: '3.8'

services:
  app:
    build: .
    container_name: orders_service
    ports:
      - "8080:8080"  # Port for GraphQL server
      - "50051:50051"  # Port for gRPC server
      - "8000:8000"  # Port for Web server
    depends_on:
      - mysql       # Depend on MySQL
      - rabbitmq    # Depend on RabbitMQ
    environment:
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orders
      DB_MAX_OPEN_CONNS: 10
      DB_MAX_IDLE_CONNS: 10
      WEB_SERVER_PORT: ":8000"
      GRPC_SERVER_PORT: 50051
      GRAPHQL_SERVER_PORT: 8080
      RABBITMQ_URL: rabbitmq
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

  mysql:
    image: mysql:8.2.0
    container_name: mysql_orders_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"  # Default MySQL port
    volumes:
      - .docker/mysql:/var/lib/mysql  # Volume for data persistence

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_service
    restart: always
    ports:
      - "5672:5672"  # Port for AMQP protocol
      - "15672:15672"  # Port for management panel
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
